title: Samuel (Sam) Daulton
description: # this means to ignore newlines until "baseurl:"

permalink: ':title/'
baseurl: "/sdaulton.github.io" # the subpath of your site, e.g. /blog
url: "https://sdaulton.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Samuel (Sam) Daulton # add your name
author-img: samuel-daulton.jpg # add your photo
about-author: Scientist and Explorer # add description
social-google: beXm1FwAAAAJ # add your google scholar handle
social-instagram: samdaulton # add your IG handle
social-facebook: # add your Facebook handle
social-github: sdaulton # add your Github handle
social-linkedin: samuel-daulton # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
